version: '3'

services:
  db:
    image: postgres
  web: &web
    build: .
    command: gunicorn nekidaem_test.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/code
      - ./static:/code/static/
    expose:
      - 8000
    depends_on:
      - db
      - rabbitmq
      - celery_worker
  rabbitmq:
    image: rabbitmq:3.7-alpine
  celery_worker:
    <<: *web
    command: celery -A nekidaem_test worker --loglevel=info
    ports: []
    depends_on:
      - rabbitmq
      - db
  nginx:
    build: ./nginx
    volumes:
      - ./static:/code/static/
    ports:
      - 1337:80
    depends_on:
      - web

volumes:
    static:



