# Generated by Django 2.2.4 on 2019-08-20 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_subscriber'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='read',
            field=models.BooleanField(default=False),
        ),
    ]
