# Generated by Django 2.2.4 on 2019-08-21 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_blog_read'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='read',
            field=models.BooleanField(),
        ),
    ]
