# Generated by Django 2.2.4 on 2019-09-25 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_read_news'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='read',
            field=models.CharField(max_length=100),
        ),
        migrations.DeleteModel(
            name='Read_News',
        ),
    ]
