# Generated by Django 2.2.4 on 2019-09-26 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_auto_20190925_0925'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='read',
        ),
    ]
