# Generated by Django 2.2.4 on 2019-09-26 07:46

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_blog_read'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='read',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={}),
        ),
    ]
