# Generated by Django 2.2.4 on 2019-09-28 13:50

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_auto_20190926_0746'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='reader_news',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='blog',
            name='read',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=list),
        ),
    ]
