# Generated by Django 2.2.4 on 2019-10-14 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0018_blog_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='email',
        ),
    ]
